version: "3.9"
services:
  db:
    image: mysql:8.4
    environment:
      MYSQL_DATABASE: studentloans
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
  backend:
    build: ./backend
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASS: root
    ports:
      - "8080:8080"
    depends_on:
      - db
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
