spring:
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:3306/studentloans
    username: ${DB_USER:root}
    password: ${DB_PASS:root}
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
server:
  port: 8080
